### ISSUE TITLE
Problems when I use createSiberObject to creat a siber object?

### ISSUE THREAD

**Issue by qinsiar** [AndrewLJackson/SIBER#27]
Hi,
When I use createSiberObject to creat a siber object, the object could not creat. And it said "Error in sort.list(y) : 'x' must be atomic for 'sort.list' Have you called 'sort' on a list?"
![image](https://cloud.githubusercontent.com/assets/17017326/25752453/56adbeb0-3186-11e7-9383-d25abb29d901.png)
pls help me how to solve it!
Thank you

**Comment by AndrewLJackson** [comment]
hi. please could you email or post some code and some data so I can investigate?

**Comment by qinsiar** [comment]
Hi Andrew,
I'm sorry for later reply. My data were attached. The codes were listed below:
set.seed(1)
library(SIBER)

season_changes_iso3 <- read_csv("C:/Users/Qin.Chuanxin/Desktop/20170425 Data from Daya Bay/season changes-iso3.csv")
Parsed with column specification:
cols(
  iso1 = col_double(),
  iso2 = col_double(),
  group = col_integer(),
  community = col_integer()

siber.example <- createSiberObject(season_changes_iso3)
Error in sort.list(y) : 'x' must be atomic for 'sort.list'
Have you called 'sort' on a list?

Thank you!
Chuanxin




------------------
 ———————————————————————————
 Visitor Scientist of Mote Marine Laboratory, Sarasota, FL, USA
Deputy director, Dr. Chuan-xin Qin
 Fishery Resources Conservation & Marine Ranching Division
South China Sea Fisheries Research Institute
 Chinese Academy of Fishery Sciences
 231 Xingangxi Road, Guangzhou, 510300
 P.R.China
Mobil phone: +8618925127968
 Email: qqincx@hotmail.com & qincx@scsfri.ac.cn & qqincx@163.com
 Do not , for one repulse , give up the purpose that you resolved to effect .(William Shakespeare , British dramatist)



 
 
 
------------------ Original ------------------

**Comment by AndrewLJackson** [comment]
hi Chuaxin

i am catching up on my SIBER requests for help and realise i didnt get back to you. Did you get this fixed? I tdont seem to be able to see the attached data and i can't replicate it. It is possible that community is expected to be sorted, but i think i coded it in a more generic manner.

best wishes

andrew

**Comment by qinsiar** [comment]
Hi Andrew,
Sure, I found I should use "data.frame" to order the data. However, the problems now are that the results, after I use "groupMetricML" and “communityMetricML” , are different with the group_name and community_name changed.
Eg: all data is same, and group name changed from seasons(spring...) to 1,2,3,4 and community name from sites name to 1,2,3.
Do you know how to fix it? I don't know which result I could believe.
Thank you!
Chuanxin






------------------
 ———————————————————————————
 Deputy director, Dr. Chuan-xin Qin
 Fishery Resources Conservation & Marine Ranching Division
South China Sea Fisheries Research Institute
 Chinese Academy of Fishery Sciences
 231 Xingangxi Road, Guangzhou, 510300
 P.R.China
Mobil phone: +8618925127968
 Email: qqincx@hotmail.com & qincx@scsfri.ac.cn & qqincx@163.com
 Do not , for one repulse , give up the purpose that you resolved to effect .(William Shakespeare , British dramatist)



 
 
 
------------------ Original ------------------

**Comment by AndrewLJackson** [comment]
hi Chuanxin

if possible could you email me the two version of your data and scripts and i will take a look please? you could email directly to a.jackson@tcd.ie<mailto:a.jackson@tcd.ie> rather than replying to this which will go to github

best wishes
andrew
--
––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 16 Aug 2017, at 19:07, qinsiar <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Andrew,
Sure, I found I should use "data.frame" to order the data. However, the problems now are that the results, after I use "groupMetricML" and “communityMetricML” , are different with the group_name and community_name changed.
Eg: all data is same, and group name changed from seasons(spring...) to 1,2,3,4 and community name from sites name to 1,2,3.
Do you know how to fix it? I don't know which result I could believe.
Thank you!
Chuanxin






------------------
———————————————————————————
Deputy director, Dr. Chuan-xin Qin
Fishery Resources Conservation & Marine Ranching Division
South China Sea Fisheries Research Institute
Chinese Academy of Fishery Sciences
231 Xingangxi Road, Guangzhou, 510300
P.R.China
Mobil phone: +8618925127968
Email: qqincx@hotmail.com<mailto:qqincx@hotmail.com> & qincx@scsfri.ac.cn<mailto:qincx@scsfri.ac.cn> & qqincx@163.com<mailto:qqincx@163.com>
Do not , for one repulse , give up the purpose that you resolved to effect .(William Shakespeare , British dramatist)






------------------ Original ------------------

**Comment by DianaSzteren** [comment]
Hi,
I get on well with the first part of your script. However, after 
plotSiberObject(siber.example,
                ax.pad = 2, 
                hulls = F, community.hulls.args, 
                ellipses = T, group.ellipses.args,
                group.hulls = F, group.hull.args,
                bty = "L",
                iso.order = c(1,2),
                xlab = expression({delta}^13*C~'\u2030'),
                ylab = expression({delta}^15*N~'\u2030')
)
it answers:
"Error in plotSiberObject(siber.example, ax.pad = 2, hulls = F, community.hulls.args,  : 
  object 'siber.example' not found "
could you please help?
Thak you very much!

**Comment by AndrewLJackson** [comment]
hi

do you have an object called siber.example in your workspace? it sounds like you probably have used createSiberObject() to make something and called it by your own nomenclature.

best wishes
andrew


--
––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 10 Sep 2017, at 18:45, DianaSzteren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I get on well with the first part of your script. However, after
plotSiberObject(siber.example,
ax.pad = 2,
hulls = F, community.hulls.args,
ellipses = T, group.ellipses.args,
group.hulls = F, group.hull.args,
bty = "L",
iso.order = c(1,2),
xlab = expression({delta}^13C~'\u2030'),
ylab = expression({delta}^15N~'\u2030')
)
it answers:
"Error in plotSiberObject(siber.example, ax.pad = 2, hulls = F, community.hulls.args, :
object 'siber.example' not found "
could you please help?
Thak you very much!
