### ISSUE TITLE
community hull polygons not appearing in plot 

### ISSUE THREAD

**Issue by BelindaCannell** [AndrewLJackson/SIBER#30]
[BB_Feath_14.xlsx](https://github.com/AndrewLJackson/SIBER/files/1469807/BB_Feath_14.xlsx)
Hi Professor Jackson, I am using SIBER for the first time, and  I am unable to get community polygons on the plot (tho' they appear when I run the demo code). I have used the code from your demo, but changed  hulls=T:
par(mfrow=c(1,1))
plotSiberObject(siber.example,
                ax.pad = 2, 
                hulls = T, community.hulls.args, 
                ellipses = T, group.ellipses.args,
                group.hulls = F, group.hull.args,
                bty = "L",
                iso.order = c(1,2),
                xlab = expression({delta}^13*C~'\u2030'),
                ylab = expression({delta}^15*N~'\u2030')
)
Also, when I run the community metrics the values for TA and SDNND are 0.00000 for each community. 
I'm sure there must be some simple explanation, but I can't find it! I have attached my data file and would appreciate your guidance on this.
Kind regards
Belinda

**Comment by AndrewLJackson** [comment]
hi belinda

my guess would be taht one or more of your communities only has two populations comprising it, which is resulting in a TA = 0, since three vertices are required to draw an enclosed polygon. Bit its hard to tell. I dont have time at the moment to look at code or data, but you could post a quick plot of your data as you want to visualise it insetead?

best wishes
andrew
--
––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 14 Nov 2017, at 06:50, BelindaCannell <notifications@github.com<mailto:notifications@github.com>> wrote:


BB_Feath_14.xlsx<https://github.com/AndrewLJackson/SIBER/files/1469807/BB_Feath_14.xlsx>
Hi Professor Jackson, I am using SIBER for the first time, and I am unable to get community polygons on the plot (tho' they appear when I run the demo code). I have used the code from your demo, but changed hulls=T:
par(mfrow=c(1,1))
plotSiberObject(siber.example,
ax.pad = 2,
hulls = T, community.hulls.args,
ellipses = T, group.ellipses.args,
group.hulls = F, group.hull.args,
bty = "L",
iso.order = c(1,2),
xlab = expression({delta}^13C~'\u2030'),
ylab = expression({delta}^15N~'\u2030')
)
Also, when I run the community metrics the values for TA and SDNND are 0.00000 for each community.
I'm sure there must be some simple explanation, but I can't find it! I have attached my data file and would appreciate your guidance on this.
Kind regards
Belinda

**Comment by BelindaCannell** [comment]
Hi Andrew
Thank you so much for your quick response. Yes there are only two groups- I knew it would be a simple explanation, but so simple I couldn’t think of it- boy do I feel dumb!
Kind regards
Belinda

Dr Belinda Cannell
Research Fellow
Oceans Institute/ Biological Sciences  •  M470, Stirling Hwy, Crawley 6009, Western Australia
T +61 8 6488 7659  •  M +61421641050  •  E belinda.cannell@uwa.edu.au
[The University of Western Australia]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/uwa-logo/>

[Pursue Impossible]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/pursue> [Facebook] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/facebook>  [Twitter] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/twitter>  [Youtube] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/youtube>

<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/campaign>

**Comment by AndrewLJackson** [comment]
always obvious in hindsight! and not dumb!
--
––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 14 Nov 2017, at 14:51, BelindaCannell <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Andrew
Thank you so much for your quick response. Yes there are only two groups- I knew it would be a simple explanation, but so simple I couldn’t think of it- boy do I feel dumb!
Kind regards
Belinda

Dr Belinda Cannell
Research Fellow
Oceans Institute/ Biological Sciences • M470, Stirling Hwy, Crawley 6009, Western Australia
T +61 8 6488 7659 • M +61421641050 • E belinda.cannell@uwa.edu.au<mailto:belinda.cannell@uwa.edu.au>
[The University of Western Australia]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/uwa-logo/>

[Pursue Impossible]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/pursue> [Facebook] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/facebook> [Twitter] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/twitter> [Youtube] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/youtube>

<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/campaign>
