### ISSUE TITLE
Point symbols in plotSiberObject

### ISSUE THREAD

**Issue by johnsonamy24** [AndrewLJackson/SIBER#32]
Hello,

I am trying to create a greyscale SIBER plot with five groups and am having trouble getting the code to work for distinguishing between the groups. I used "palette()" with 5 categories and can make 5 shades of grey/black, but can't get 5 symbols. Ideally, I want one symbol for each of the 5 groups (and will have some grey and some black). I have read the customizing plots manually page and used the code:

plotSiberObject(siber.example,
                  ax.pad = 2, 
                  hulls = FALSE, 
                  ellipses = FALSE,
                  group.hulls = FALSE,
                  bty = "L",
                  iso.order = c(1,2),
                  xlab = expression({delta}^13*C~'\u2030'),
                  ylab = expression({delta}^15*N~'\u2030'),
                  points.order = c(24,22,21,20,19)
                  )

But I only end up with the first point type (24) showing up (i.e., all points are open triangles). If I change the first points.order value to another number, then all the points will be that type. But I can't get it to change the points based on group type - I want each of the 5 groups to have different symbols. Is there a way to make this work?

Thank you!

**Comment by AndrewLJackson** [comment]
hi

the points.order argument specifies the point type to be used for each community, and doesnt extend down into the groups.

if you want different points per group you need to plot teh data yourself using the base function something like

plot(d15N ~ d13C, pch = mypoints[group], col = group, data = mydata)

then the addEllipse() function can be used to draw on top of this

On 16 Feb 2018, at 06:15, johnsonamy24 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I am trying to create a greyscale SIBER plot with five groups and am having trouble getting the code to work for distinguishing between the groups. I used "palette()" with 5 categories and can make 5 shades of grey/black, but can't get 5 symbols. Ideally, I want one symbol for each of the 5 groups (and will have some grey and some black). I have read the customizing plots manually page and used the code:

plotSiberObject(siber.example,
ax.pad = 2,
hulls = FALSE,
ellipses = FALSE,
group.hulls = FALSE,
bty = "L",
iso.order = c(1,2),
xlab = expression({delta}^13C~'\u2030'),
ylab = expression({delta}^15N~'\u2030'),
points.order = c(24,22,21,20,19)
)

But I only end up with the first point type (24) showing up (i.e., all points are open triangles). If I change the first points.order value to another number, then all the points will be that type. But I can't get it to change the points based on group type - I want each of the 5 groups to have different symbols. Is there a way to make this work?

Thank you!

**Comment by daudi-msafiri** [comment]
Dear Andrew,
Thanks so much! Just for clarification (because I actually am struggling with an identical issue): 

plot(d15N ~ d13C, pch = mypoints[group], col = group, data = my data)

Does this get written into the plotSiberObject() argument or is that a subset of the addEllipse() set of arguments? I also don't understand what "mypoints" are in this case...is it siber.example? Maybe a bit of actual code with siber.example will clarify what you mean.

In my case, I have two communities and three groups and I want to plot the communities with open and closed symbols (groups will determine whether they are red squares, blue circles or black triangles). When I code the symbols correctly, I lose the color scheme I want; when I code the colors correctly, I lose the symbols. I am just missing where to correctly insert the code.

Just for extra context, here is an example of one of my addEllipse() arguments. I have six of these structured identically:

c.id <- 2 # community ID
g.id <- 3 # group ID within that community

gr1 <- addEllipse(siber.cameroon$ML.mu[[c.id]][ , , g.id],
                  siber.cameroon$ML.cov[[c.id]][ , , g.id],
                  m = NULL,
                  n = 1000,
                  p.interval = 0.95,
                  ci.mean = FALSE,
                  col = (g.id = 3),
                  lty = 3,
                  lwd = 2)

**Comment by AndrewLJackson** [comment]
hi

mypoints would be something like

mypoints <- c(1, 2) # define the two point types for each of your communities

and then assuming community is coded 1 or 2, and group is coded 1, 2, 3

plot( d15N ~ d13C, pch = mypoints[community], col = group, data = mydata )

then you should get a plot with point types determined by the column of community data, adn the colour determined by the group identifier.

then you use addEllipse() to add ellipses of the correct colour to each group




On 18 Feb 2018, at 01:33, daudi-msafiri <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Andrew,
Thanks so much! Just for clarification (because I actually am struggling with an identical issue):

plot(d15N ~ d13C, pch = mypoints[group], col = group, data = my data)

Does this get written into the plotSiberObject() argument or is that a subset of the addEllipse() set of arguments? I also don't understand what "mypoints" are in this case...is it siber.example? Maybe a bit of actual code with siber.example will clarify what you mean.

In my case, I have two communities and three groups and I want to plot the communities with open and closed symbols (groups will determine whether they are red squares, blue circles or black triangles). When I code the symbols correctly, I lose the color scheme I want; when I code the colors correctly, I lose the symbols. I am just missing where to correctly insert the code.

Just for extra context, here is an example of one of my addEllipse() arguments. I have six of these structured identically:

c.id<http://c.id> <- 2 # community ID
g.id<http://g.id> <- 3 # group ID within that community

gr1 <- addEllipse(siber.cameroon$ML.mu[[c.id<http://c.id>]][ , , g.id<http://g.id>],
siber.cameroon$ML.cov[[c.id<http://c.id>]][ , , g.id<http://g.id>],
m = NULL,
n = 1000,
p.interval = 0.95,
ci.mean = FALSE,
col = (g.id<http://g.id> = 3),
lty = 3,
lwd = 2)

**Comment by daudi-msafiri** [comment]
It all makes sense, but...
> plot(d15N ~ d13C, pch = mypoints[community], col = group, data = siber.cameroon)

gives me...

Error in FUN(X[[i]], ...) : object 'community' not found

I triple checked my csv file and "community" is the correct header. (I attached a text file with my actual data points just for confirmation purposes. I'm also dropping in a screen shot that shows my output of list(siber.cameroon), which should show that everything is keyed in and reading correctly.)

Again, I feel like I am one tiny step from getting this to work, but just can't get seem to crack that last bit of code that it will take to get me over the finish line.

Thanks again for your help, Andrew!

![screen shot 2018-02-22 at 1 17 14 pm](https://user-images.githubusercontent.com/36579532/36520157-bc63d8b0-17d2-11e8-9ba8-c76a24ebea81.png)


[com1type2.txt](https://github.com/AndrewLJackson/SIBER/files/1746564/com1type2.txt)
