### ISSUE TITLE
Add Legend to plotSiberObject

### ISSUE THREAD

**Issue by valybionda** [AndrewLJackson/SIBER#33]
Hi,
I have a problem adding the legend in the siberobj. It seems that group names are randomly assigned (and not the right one...):

plot the siberobj:
siber.obj <- createSiberObject(mydata)
community.hulls.args <- list(col = 1, lty = 1, lwd = 1)
group.ellipses.args  <- list(n = 100, p.interval = 0.95, lty = 1, lwd = 2)
group.hull.args      <- list(lty = 2, col = "grey20")
par(mfrow=c(1,1))
plotSiberObject(siber.obj,
                ax.pad = 2, 
                hulls = F, community.hulls.args, 
                ellipses = T, group.ellipses.args,
                group.hulls = T, group.hull.args,
                bty = "L",
                iso.order = c(1,2),
                xlab=expression({delta}^13*C~'\u2030'),
                ylab=expression({delta}^15*N~'\u2030'),
                cex = 0.5   
)

to add the legend, I use:

legend("topleft",
       as.character(paste("Group ",unique(group))),
       pch=19,
       col=1:length(unique(group))) 

I don't know what can cause this difference...

Thank you

**Comment by AndrewLJackson** [comment]
hi Valentina

im pretty sure the ordering within siber of the plots is first by community, and then by group within community. You always have to be very careful when using base graphics and the legend function, since it relies on some faith, or preferably diligence on the part of the user to make sure the orders are correct.. So while the order of your groups in your raw data file might be in ordered strictly by group, in siber they are reorded into community:group.

In the vignette SIBER::Introduction-to-SIBER an object called siber.example is created. The ordering of the groups is defined in siber.example$group.names which returns a list of length of the number of communities with the name of each list object matching the labelling in your raw data. Within each of these list objects is a vector of length equal to the number of groups in that community along with their names. You should be able to use this to specify the colours and point types for the legend object you create.

Alternatively, you might prefer to use ggplot2 along the lines of the attached example

best wishes

andrew

––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 9 Mar 2018, at 09:45, Valentina <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I have a problem adding the legend in the siberobj. It seems that group names are randomly assigned (and not the right one...):

plot the siberobj:
siber.obj <- createSiberObject(mydata)
community.hulls.args <- list(col = 1, lty = 1, lwd = 1)
group.ellipses.args <- list(n = 100, p.interval = 0.95, lty = 1, lwd = 2)
group.hull.args <- list(lty = 2, col = "grey20")
par(mfrow=c(1,1))
plotSiberObject(siber.obj,
ax.pad = 2,
hulls = F, community.hulls.args,
ellipses = T, group.ellipses.args,
group.hulls = T, group.hull.args,
bty = "L",
iso.order = c(1,2),
xlab=expression({delta}^13C~'\u2030'),
ylab=expression({delta}^15N~'\u2030'),
cex = 0.5
)

to add the legend, I use:

legend("topleft",
as.character(paste("Group ",unique(group))),
pch=19,
col=1:length(unique(group)))

I don't know what can cause this difference...

Thank you

**Comment by valybionda** [comment]
Thank you!
So I checked my "siber.example$group.names" and I solved the problem coming back to my original matrix and putting the data (community:group) in alphabetical order (and adding a note in my script to remember that!).
As you said I could use ggplot2, but I'm not sure how to add ellipses in my biplot. Do you have some examples of that?

**Comment by AndrewLJackson** [comment]
hi valentina

drop me an email directly to jacksoan@tcd.ie<mailto:jacksoan@tcd.ie> and i will send you on an example using ggplot2 with ellipses. Its not entirely straight forward to implement, and i am have plans to recode SIBER to work with ggplot2 and dplyr and tidyr etc… but that will take me some time to implement

best wishes

andrew

––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 9 Mar 2018, at 11:31, Valentina <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you!
So I checked my "siber.example$group.names" and I solved the problem coming back to my original matrix and putting the data (community:group) in alphabetical order (and adding a note in my script to remember that!).
As you said I could use ggplot2, but I'm not sure how to add ellipses in my biplot. Do you have some examples of that?
