### ISSUE TITLE
SIBER no longer exists?

### ISSUE THREAD

**Issue by melizaantunes** [AndrewLJackson/SIBER#49]
Hi Andrew!
I've been trying to download the SIBER package again (because I had to restore my computer) and I couldn't do this.. The package is not avaliable anymore?

Thanks a lot

Maria

**Comment by AndrewLJackson** [comment]
It’s a mistake on my part. I’m in process of posting it again to CRAN. you can install from GitHub in the meantime.



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 13 Feb 2019, at 17:34, melizaantunes <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Andrew!
I've been trying to download the SIBER package again (because I had to restore my computer) and I couldn't do this.. The package is not avaliable anymore?

Thanks a lot

Maria

**Comment by melizaantunes** [comment]
Got it!! What a fright hehe
Thank you for the layout and all the help! Good luck then

Thank you!

**Comment by melizaantunes** [comment]
Hi Andrew, it's me again
Do you have an estimative of when you'll be able to add siber back to Cran? I'm asking because we're using it in order to finish a paper and try and get it published, and I still have some data I need to run.
I appreciate it so much the way SIBER is helping me that I just cannot imagine myself getting it done without it.

thanks a lot, and i'm sorry for bothering you, I'm just desperate
Maria

**Comment by AndrewLJackson** [comment]
Hi

You can always download any release version and install from github. https://github.com/AndrewLJackson/SIBER/releases

Or you can install the latest development version.

I don’t know yet when it will be back on cran

Best wishes
Andrew



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 18 Feb 2019, at 20:13, melizaantunes <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Andrew, it's me again
Do you have an estimative of when you'll be able to add siber back to Cran? I'm asking because we're using it in order to finish a paper and try and get it published, and I still have some data I need to run.
I appreciate it so much the way SIBER is helping me that I just cannot imagine myself getting it done without it.

thanks a lot, and i'm sorry for bothering you, I'm just desperate
Maria
