### ISSUE TITLE
Legend in italics

### ISSUE THREAD

**Issue by ninonmavraki** [AndrewLJackson/SIBER#55]
Dear Andrew,

I am trying to find a way to make the legend in the isotopic plot in italics. Since my ellipses are generated by isotopic signatures deriving from specific species, I would like to have the names of the species in italics. Is this possible? I could not find the code anywhere and I was wondering whether you could help me.

Thank you in advance!

Best regards,

Ninon

**Comment by AndrewLJackson** [comment]
Dear Ninon

The answer is here https://r.789695.n4.nabble.com/changing-font-to-italic-for-one-entry-in-legend-td4632749.html

Best wishes

Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 21 Aug 2019, at 10:02, ninonmavraki <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Andrew,

I am trying to find a way to make the legend in the isotopic plot in italics. Since my ellipses are generated by isotopic signatures deriving from specific species, I would like to have the names of the species in italics. Is this possible? I could not find the code anywhere and I was wondering whether you could help me.

Thank you in advance!

Best regards,

Ninon

**Comment by ninonmavraki** [comment]
Hi Andrew,

I am sorry but I cannot see the answer. There is this Paul who provided the
answer but the answer is somehow hidden. Do you happen to have another link?

Thank you in advance.

Best regards,

Ninon

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by AndrewLJackson** [comment]
customised plots is not something that is fully supported within SIBER. Instructions on how to build custom isotope plots in `ggplot2` is provided here https://github.com/andrewcparnell/simms_course/blob/master/aj-content/practicals/day-1-pm1/first-biplot.Rmd
