### ISSUE TITLE
Clairification - SIBER works without SIAR??

### ISSUE THREAD

**Issue by naalipalo** [AndrewLJackson/SIBER#57]
Ive had an accident on my computer and had to reload all packages.  I did not reload SIAR since your other site says DO NOT USE...except it seems now that SIBER functions do not work.  Ive got SIMMR and SIBER on but no SIAR.  When I run the script in SIBER, I get to the function standard.ellipse and it tells me:

Error in standard.ellipse(spx[[j]], spy[[j]], steps = 1) : 
  could not find function "standard.ellipse"
> ?standard.ellipse
No documentation for ‘standard.ellipse’ in specified packages and libraries:
you could try ‘??standard.ellipse’
> ??standard.ellipse

So I am going to load the SIAR package, and hopefully this will fix the issue, but you should note that even though you said SIAR is not being used SIBER is still dependent upon it (it seems).  Would running the ellipse library fix this issue instead of SIAR?

**Comment by AndrewLJackson** [comment]
hi
That is very odd. The only instance of code `standard.ellipse` that I see in the SIBER package is in a file in SIBER/tmp/StandardEllipseCalc.R which is not part of the package build so should never appear.

What version of SIBER have you got installed? Latest is 2.1.4

What function caused that error?

Best wishes
Andrew

--
Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by naalipalo** [comment]
OK, so I have been working on trying to create a script to run my data through all of this and was given an older script. Also, Ive been watching your siber.elipse pod cast.  It has

for (j in unique(group)){  
  # Fit a standard ellipse to the data
  SE <- standard.ellipse(spx[[j]],spy[[j]],steps=1)
  
  # Extract the estimated SEA and SEAc from this object
  SEA[j] <- SE$SEA
  SEAc[j] <- SE$SEAc
  
  # plot the standard ellipse with d.f. = 2 (i.e. SEAc)
  # These are plotted here as thick solid lines
  lines(SE$xSEAc,SE$ySEAc,col=j,lty=1,lwd=3)
for coding instructions.  In trying to answer your reply, I just noticed that you loaded the package siar, though it was doing the siber ellipses in it....so that could explain a bunch.Apologize for the confusion.  

~K



 

    On Wednesday, January 15, 2020, 12:26:37 AM AKST, Andrew Jackson <notifications@github.com> wrote:  
 
 hi
That is very odd. The only instance of code `standard.ellipse` that I see in the SIBER package is in a file in SIBER/tmp/StandardEllipseCalc.R which is not part of the package build so should never appear.

What version of SIBER have you got installed? Latest is 2.1.4

What function caused that error?

Best wishes
Andrew

--
Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by AndrewLJackson** [comment]
Those podcasts and all old code from siar is a very long time out of date as per the github page for SIBER.  You can use the podcasts for the concepts which are the same. There are extensive vignettes in SIBER explaining all the current functionality



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 15 Jan 2020, at 20:43, naalipalo <notifications@github.com> wrote:

﻿OK, so I have been working on trying to create a script to run my data through all of this and was given an older script. Also, Ive been watching your siber.elipse pod cast.  It has

for (j in unique(group)){
  # Fit a standard ellipse to the data
  SE <- standard.ellipse(spx[[j]],spy[[j]],steps=1)

  # Extract the estimated SEA and SEAc from this object
  SEA[j] <- SE$SEA
  SEAc[j] <- SE$SEAc

  # plot the standard ellipse with d.f. = 2 (i.e. SEAc)
  # These are plotted here as thick solid lines
  lines(SE$xSEAc,SE$ySEAc,col=j,lty=1,lwd=3)
for coding instructions.  In trying to answer your reply, I just noticed that you loaded the package siar, though it was doing the siber ellipses in it....so that could explain a bunch.Apologize for the confusion.

~K





On Wednesday, January 15, 2020, 12:26:37 AM AKST, Andrew Jackson <notifications@github.com> wrote:

hi
That is very odd. The only instance of code `standard.ellipse` that I see in the SIBER package is in a file in SIBER/tmp/StandardEllipseCalc.R which is not part of the package build so should never appear.

What version of SIBER have you got installed? Latest is 2.1.4

What function caused that error?

Best wishes
Andrew

--
Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/
