### ISSUE TITLE
Question about bayesianLayman function

### ISSUE THREAD

**Issue by bsharris381** [AndrewLJackson/SIBER#60]
Hello Andrew,

I posted a question awhile back and you quickly provided me code that worked great and saved me a lot of time.  The question was about using layman metrics for comparisons of each group of a community rather than just for each community.  I'm interested in differences among groups between two river sections with different stressors, not the entire community between reaches.

I had a colleague do a friendly review of my manuscript, and they asked why I didn't do the Layman metrics that incorporated the Bayesian estimate (bayesianLayman) versus the point estimates (laymanMetrics).  I'm not too handy with R (so forgive my ignorance if there is a simple solution), so the only way that I can think to do this would be to run a single species through and have each community represent a river and river reach.  C1 = river one, reach one, C2 = river one reach two, etc.   Is there a way to specify/extract the Layman metrics for each group of a community when running through the posterior ellipses, extracting posterior means, and then running bayesianLayman similar to doing it only for a community like in the example code?

THANK YOU,

Brandon

**Comment by AndrewLJackson** [comment]
Hi Brandon

In short, no. This is not possible. You can’t calculate error around a metric like convex hull area, No more than you can for max or min using max likelihood, or Bayesian or anything. The only black magic that could be applied is bootstrapping some how but I’m not a fan.

Back over to your collegiate reviewer if they have another idea

Best wishes
Andrew



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 10 Apr 2020, at 16:39, bsharris381 <notifications@github.com> wrote:

﻿

Hello Andrew,

I posted a question awhile back and you quickly provided me code that worked great and saved me a lot of time. The question was about using layman metrics for comparisons of each group of a community rather than just for each community. I'm interested in differences among groups between two river sections with different stressors, not the entire community between reaches.

I had a colleague do a friendly review of my manuscript, and they asked why I didn't do the Layman metrics that incorporated the Bayesian estimate (bayesianLayman) versus the point estimates (laymanMetrics). I'm not too handy with R (so forgive my ignorance if there is a simple solution), so the only way that I can think to do this would be to run a single species through and have each community represent a river and river reach. C1 = river one, reach one, C2 = river one reach two, etc. Is there a way to specify/extract the Layman metrics for each group of a community when running through the posterior ellipses, extracting posterior means, and then running bayesianLayman similar to doing it only for a community like in the example code?

THANK YOU,

Brandon

**Comment by bsharris381** [comment]
Thanks Andrew,

I followed up with my friendly reviewer about his suggestion.  It sounds like he was interpreting metrics with a subscript b from the Coulter et al. (2019) paper (the authors used your R package).  Like you said, the b represents boot strapping and not Bayesian.

My plan is to stick with my original comparison of Layman ML point estimates and not do the boot strapping per your suggestion.

Have a nice weekend!

Brandon


Brandon S. Harris


Assistant Scientist, Large River Fisheries Ecology

Illinois Natural History Survey - Yorkville, IL

bsharris@illinois.edu


Office located at:

Illinois River Biological Station

704 N. Schrader Ave.

Havana, IL 62644



________________________________
