### ISSUE TITLE
CreateSiberObject error

### ISSUE THREAD

**Issue by 68lau** [AndrewLJackson/SIBER#63]
Hi there,

My first time running SIBER. I did the demo run and everything worked fine. Imported my own data in csv. format using the demo.siber.data.csv file as a template. Then ran the following code:

View(custom_siber_data)
mydata <- custom_siber_data
siber.example <- createSiberObject(mydata)

This is followed by an error message:

Error in if (xi > xj) 1L else -1L : missing value where TRUE/FALSE needed
In addition: Warning message:
In Ops.factor(xi, xj) : ‘>’ not meaningful for factors

I have no idea what the error message even means. Am I missing something obvious?

Thank you in advance!

**Comment by AndrewLJackson** [comment]
hi, i will need a minimum working example to illustrate this error. It lies in functions below SIBER and i cant tell what is throwing it.

**Comment by popovs** [comment]
I was having this same issue. Assuming the structure of your data lines up with the example (e.g. `str(mydata)` looks the same as `str(demo.siber.data)`) try `mydata <- droplevels(mydata)` before creating your SIBER object. In my case the unused factors in my data were causing a mismatch between the size of the matrix `createSiberObject` creates vs. what was actually in the data.

**Comment by nlink33** [comment]
I am having the same issue. I tried droplevels as suggested, but that did not fix the issue. I have attached the data I am trying to work with. Thank you in advance!

[SIBERdata.xlsx](https://github.com/AndrewLJackson/SIBER/files/5042484/SIBERdata.xlsx)

**Comment by nlink33** [comment]
I had the same issue and droplevels didn't work for me. Instead, I loaded my data file from CSV format instead of an Excel file and that fixed it!

**Comment by naalipalo** [comment]
This is very odd because I too was getting this error. Only, I got the error on 1 of 2 scripts. Both scripts use the same input file, its just one I used library (readr) which I can use read_csv it brings in the csv with column specifications. Whereas simply putting in using read.csv had no auto structural formatting and it made all the difference. SIBER doesn't work well with readr objects??

**Comment by AndrewLJackson** [comment]
I have not tested it with readr objects so there could well be an issue if it not a data.frame class object.



--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | ***@***.******@***.***>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

From: naalipalo ***@***.***>
Date: Tuesday, 25 May 2021 at 02:06
To: AndrewLJackson/SIBER ***@***.***>
Cc: Andrew Jackson ***@***.***>, Comment ***@***.***>
Subject: Re: [AndrewLJackson/SIBER] CreateSiberObject error (#63)

This is very odd because I too was getting this error. Only, I got the error on 1 of 2 scripts. Both scripts use the same input file, its just one I used library (readr) which I can use read_csv it brings in the csv with column specifications. Whereas simply putting in using read.csv had no auto structural formatting and it made all the difference. SIBER doesn't work well with readr objects??

**Comment by maximeG6** [comment]
hello everyone, when this issue occur for me, i have to change only my isotopes data with a "." and no a ",". I think when we change a .xls in .csv this provide a probleme. (sorry for my english..., i am a french student in master degree). And i am agree with the problem that xls occur (readxl package).

**Comment by baylorlynch** [comment]
Hello,
I recently ran into the same issue. I was bringing in data using read.csv and was getting the error above. I tried the suggestions above, but I didn't get any success. However, after adding ", header=T" to my readr code, I got my code to run without error.

Full code I used below.....

SIBER <- read.csv("G:/My Drive/Palaemon Research/Palaemon/Master Data/SIBER.csv", header=T)

**Comment by Wotapoint** [comment]
I had the same error and by using the as.data.frame() command I was able to create the object

**Comment by AndrewLJackson** [comment]
Check of class of data object passed to createSiberObject has been added to the development version of SIBER and will be rolled into the next release. It will automatically coerce a tibble to data.frame only class and issue a warning to this effect. Thanks.
