### ISSUE TITLE
About theoretical aspects in SIBER 

### ISSUE THREAD

**Issue by AylenM** [AndrewLJackson/SIBER#85]
Hello! I am writing because I am a bit lost in SIBER. I have theoretical and practical doubts, and I think this group could help me in solving them.
1) What kind of "Standard Ellipse" generates the code: "group.ellipses.args <- list(n = 100, p.interval = 0.95, lty = 1, lwd = 2)"? Because that's what in the script is plotted with plotSiberObject. Would it be SEA, with 95% of the data? Or if you change the p.interval to 0.40 would you get SEAc? I understand that SE is not the same as SEA, but I interpret that you first have to generate an ellipse before calculating its area.
2) What difference would there be between the function "group.ellipses.args" and "addEllipse"?
Not all the papers I have seen specifically express how they plotted the ellipses, or how many data are in the ellipse. 
3) I interpret that the utility of SEAb is to be comparable to any sample, rather than SEAc. Is this correct? I don't realize why it is convenient to do the analyses with values from posterior distributions (bayesian).
4) Related to the above, what is the correct interpretation when using maxLikOverlap instead of bayesianOverlap? I assumed that using maxLikOverlap comparisons is referring to SEA. Instead, bayesianOverlap, since they are estimates, they have better support for being compared between groups with different n.

Thanks in advance!!!

**Comment by naalipalo** [comment]
I hope i am not directing you wrong here, but to address part of question 1.... SEAc is the area corrected for small sample sizes. The way I understand this ellipse is similar to a kernel density plot where isopleths (ellipse polygons) are generated and if you ask for 95%,  it produces an isopleth that encompasses 95% of the data. The 0.4 was defined by SIBER as the "core" of that density plot, so it is producing an isopleth that encompasses 40%.

**Comment by AylenM** [comment]
¡Thank you for your comment!
I still don´t have the exact answers to the other questions.

**Comment by AndrewLJackson** [comment]
hi
some answers which admittedly are rather late. 

1. With p.interval=0.95 you are creating and plotting ellipses that contain approximately 95% of the data. If you set p.interval=NULL which is the default you will get the SEA ellipse. 
2. "group.ellipses.args" is not a function. it is a collection of arguments passed onwards by the function "plotGroupEllipses" through to the function "addEllipse"
3. SEAb provides the only easy way to compare the size of two ellipses with each other. This is because SEAc is a point estimate and has no uncertainty attached to it, and therefore there is no statistical intpretaiton to be made beyond one is larger than the other. 
4. The same concept applies to maximum likelihood overlap which is again a point estimate, whereas the Bayesian equivalent has uncertainty and therefore a statistical statement can be made about the the magnitude or probability of their difference.

**Comment by joanmoreaux** [comment]
Hi there,
This is very useful, thank you for those questions and answers. A follow up question regarding the group metrics: Are the estimates of SEA and SEAc always calculated with p.interval = 0.4? And is there a way to test other values for p.interval? 
Thank you for your help!

**Comment by AndrewLJackson** [comment]
Hi

By definition SEA and SEAc are standard ellipses and contain `pchisq(1, 2)` ~= 0.39 of the data.

For comparisons of size (or shape) there is no change in results whether you change the size of the ellipses to contain any X% of the data, since it involves a multiplier that would be fixed across all ellipses.

The multiplier for the standard ellipse area is `qchisq(p, df=2)` where p is the desired proportion of the data, and when `p <-  pchisq(1, 2)` the multiplier is exactly 1. For values of p less than `pchisq(1, 2)` the multiplier is <1 and so the ellipse area is smaller, and for values of p greater than `pchisq(1, 2)` the multiplier is >1 and so the ellipse area is larger.

The only quantitative difference occurs for consideration of overlap where choice of ellipse size is likely to have substantial effect on the results and hence their interpretation. There is code in the vignettes to illustrate how to achieve this.

Best wishes

Andrew

From: joanmoreaux ***@***.***>
Date: Thursday, 25 April 2024 at 18:20
To: AndrewLJackson/SIBER ***@***.***>
Cc: Andrew Jackson ***@***.***>, State change ***@***.***>
Subject: Re: [AndrewLJackson/SIBER] About theoretical aspects in SIBER (Issue #85)

Hi there,
This is very useful, thank you for those questions and answers. A follow up question regarding the group metrics: Are the estimates of SEA and SEAc always calculated with p.interval = 0.4? And is there a way to test other values for p.interval?
Thank you for your help!
