### ISSUE TITLE
Error in calculating Layman metrics : Error in hdrcde::hdr(dat[, j], probs, h = stats::bw.nrd0(dat[, j])) :    Insufficient data

### ISSUE THREAD

**Issue by fpasotti** [AndrewLJackson/SIBER#98]
Dear Andrew, dear colleagues,
I am encountering an issue which I don't seem to find be able to solve or to understand. I am working with confidential data so I will try to explain what is my issue. 

I wish to analyse the d13C and d15N of four different size class organisms (4 Taxa, my SIBER community) across a large area therefore one location (my SIBER group). 
I could easily calculate the Siberobject and create my ggplot with the ellipses and also estimate the Bayesian TA for each community with SEAB and all the posterior probabilities.

When I try though to calculate the Layman metrics with the following codes
# extract the posterior means
mu.post <- extractPosteriorMeans(siber.example, ellipses.posterior)

# calculate the corresponding distribution of layman metrics
layman.B <- bayesianLayman(mu.post)

I get a mu.post with a list of 4 with values, but a layman.B with a list of 4 with only 0
and when I try to us Siberplot I get this
Error in hdrcde::hdr(dat[, j], probs, h = stats::bw.nrd0(dat[, j])) : 
  Insufficient data

I do indeed have in one of the communities only  4 observations  but for the others I do have at least 13 observations (individual samples). I am working with pooled fauna (meiofauna) and replicated samples for Taxa. 

Is it possible to help me? 

I really appreciate since I am confused whether it is a data limitation or if I am not seeing another mistake...

Best regards,
<img width="1097" alt="Screenshot 2023-08-08 at 12 10 14" src="https://github.com/AndrewLJackson/SIBER/assets/51359033/5de25268-6c5d-4a75-adda-edb4f09ef649">
<img width="972" alt="Screenshot 2023-08-08 at 12 10 30" src="https://github.com/AndrewLJackson/SIBER/assets/51359033/3a426936-c1b8-4baf-92da-7301e20d3d3a">

**Comment by AndrewLJackson** [comment]
Hi

This looks like some sort of error or problem in the data or model setup.

Could you send me directly please a minimum working example to include a script and data so I can reproduce your outcome on my computer?

Best wishes
Andrew

From: fpasotti ***@***.***>
Date: Tuesday, 8 August 2023 at 11:15
To: AndrewLJackson/SIBER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndrewLJackson/SIBER] Error in calculating Layman metrics : Error in hdrcde::hdr(dat[, j], probs, h = stats::bw.nrd0(dat[, j])) : Insufficient data (Issue #98)

Dear Andrew, dear colleagues,
I am encountering an issue which I don't seem to find be able to solve or to understand. I am working with confidential data so I will try to explain what is my issue.

I wish to analyse the d13C and d15N of four different size class organisms (4 Taxa, my SIBER community) across a large area therefore one location (my SIBER group).
I could easily calculate the Siberobject and create my ggplot with the ellipses and also estimate the Bayesian TA for each community with SEAB and all the posterior probabilities.

When I try though to calculate the Layman metrics with the following codes

extract the posterior means

mu.post <- extractPosteriorMeans(siber.example, ellipses.posterior)

calculate the corresponding distribution of layman metrics

layman.B <- bayesianLayman(mu.post)

I get a mu.post with a list of 4 with values, but a layman.B with a list of 4 with only 0
and when I try to us Siberplot I get this
Error in hdrcde::hdr(dat[, j], probs, h = stats::bw.nrd0(dat[, j])) :
Insufficient data

I do indeed have in one of the communities only 4 observations but for the others I do have at least 13 observations (individual samples). I am working with pooled fauna (meiofauna) and replicated samples for Taxa.

Is it possible to help me?

I really appreciate since I am confused whether it is a data limitation or if I am not seeing another mistake...

Best regards,
[Image removed by sender. Screenshot 2023-08-08 at 12 10 14]<https://user-images.githubusercontent.com/51359033/259066891-5de25268-6c5d-4a75-adda-edb4f09ef649.png>
[Image removed by sender. Screenshot 2023-08-08 at 12 10 30]<https://user-images.githubusercontent.com/51359033/259066920-3a426936-c1b8-4baf-92da-7301e20d3d3a.png>

**Comment by fpasotti** [comment]
Dear Andrew I will send you the data with my code in an email, thank you so much for wishing to help me address this.

Best regards,
Francesca

**Comment by fpasotti** [comment]
Dear Andrew, please see your email for the data and code.
I send from a agent.be account.

Best regards,
Francesca

**Comment by AndrewLJackson** [comment]
Hi

I see the problem.

You have two communities but only one group within each community. It is impossible to calculate community level metrics (layman metrics as I call them) with anything less than 3 groups per community.

This is why

community.ML <- communityMetricsML(siber.example)
print(community.ML)

returns zeros or NAs. The vignette “Intro to SIBER” does not mention this explicitly, but it is clear that the community metrics are calculated using the means of the groups within that community, and anything less than 3 groups is meaningless for several of the metrics.

Best wishes
Andrew

From: fpasotti ***@***.***>
Date: Sunday, 13 August 2023 at 13:51
To: AndrewLJackson/SIBER ***@***.***>
Cc: Andrew Jackson ***@***.***>, Comment ***@***.***>
Subject: Re: [AndrewLJackson/SIBER] Error in calculating Layman metrics : Error in hdrcde::hdr(dat[, j], probs, h = stats::bw.nrd0(dat[, j])) : Insufficient data (Issue #98)

Dear Andrew, please see your email for the data and code.
I send from a agent.be account.

Best regards,
Francesca

**Comment by AndrewLJackson** [comment]
see also the FAQ https://github.com/AndrewLJackson/SIBER
